from __future__ import annotations
from collections import defaultdict
from typing import Any

from aurora_compiler.models.aurora import AuroraElement, clean_duplicate_name, slugify
from aurora_compiler.foundry.templates import base_item
from aurora_compiler.foundry import advancement as adv
from aurora_compiler.compiler.feature_linker import parse_level, is_asi_feature_id, is_artillerist_cannon_option_id

# Aurora uses "supports" labels to connect an Archetype to a class.
# Foundry uses system.classIdentifier on the subclass item.
SUPPORT_TO_CLASS_IDENTIFIER = {
    "arcane tradition": "wizard",
    "artificer specialist": "artificer",
    "primal path": "barbarian",
    "bard college": "bard",
    "divine domain": "cleric",
    "druid circle": "druid",
    "martial archetype": "fighter",
    "monastic tradition": "monk",
    "sacred oath": "paladin",
    "ranger archetype": "ranger",
    "ranger conclave": "ranger",
    "roguish archetype": "rogue",
    "sorcerous origin": "sorcerer",
    "otherworldly patron": "warlock",
    "warlock patron": "warlock",
    "blood hunter order": "blood-hunter",
    "blood hunter order (2020)": "blood-hunter",
    "mystic order": "mystic",
}

# Fallbacks from common Aurora IDs / file paths when supports is missing or custom.
ID_HINT_TO_CLASS_IDENTIFIER = [
    ("ARTIFICER", "artificer"),
    ("BARBARIAN", "barbarian"),
    ("BARD", "bard"),
    ("BLOOD_HUNTER", "blood-hunter"),
    ("CLERIC", "cleric"),
    ("DRUID", "druid"),
    ("FIGHTER", "fighter"),
    ("MONK", "monk"),
    ("PALADIN", "paladin"),
    ("RANGER", "ranger"),
    ("ROGUE", "rogue"),
    ("SORCERER", "sorcerer"),
    ("WARLOCK", "warlock"),
    ("WIZARD", "wizard"),
    ("MYSTIC", "mystic"),
]

PATH_HINT_TO_CLASS_IDENTIFIER = [
    ("artificer", "artificer"),
    ("barbarian", "barbarian"),
    ("bard", "bard"),
    ("blood", "blood-hunter"),
    ("cleric", "cleric"),
    ("druid", "druid"),
    ("fighter", "fighter"),
    ("monk", "monk"),
    ("paladin", "paladin"),
    ("ranger", "ranger"),
    ("rogue", "rogue"),
    ("sorcerer", "sorcerer"),
    ("warlock", "warlock"),
    ("wizard", "wizard"),
    ("mystic", "mystic"),
]

# Extra Aurora community/source packs often define a whole custom class plus
# archetypes, but the archetypes may only carry a source code instead of a
# normal supports label.  These are real parent class identifiers generated by
# the class compiler for the same input set.
SOURCE_HINT_TO_CLASS_IDENTIFIER = {
    "MUSG": "factotum",
    "AASM": "swordmage",
    "HSPRT": "spiritualist",
    "GPGW": "grave-warden",
    "PUGL": "pugilist",
    "TCC": "cook",
    "HMGS": "magus",
    "WS": "weaveshaper",
}

NAME_HINT_TO_CLASS_IDENTIFIER = [
    (("alchemist", "gunsmith"), "artificer"),
    (("lore of the hero", "lore of the theurge"), "factotum"),
    (("battlemage", "eldritch archer", "spellsword"), "swordmage"),
    (("beast & briar", "bloody blade", "plague & poison"), "spiritualist"),
    (("requiem of the ash", "requiem of the frigid", "requiem of the haunt", "requiem of the torpor"), "grave-warden"),
    (("arena royal", "bloodhound bruisers", "dog and hound", "salt and vinegar", "the squared circle", "the sweet science", "hand of dread", "whiskey fist"), "pugilist"),
    (("sous chef", "mess sergeant", "hash slinger", "brewmeister", "monster masher"), "cook"),
    (("the arcane order", "the knights stygian", "the primordial seal", "the shadow court", "the sidereal cabal", "the sylvan circle"), "magus"),
    (("crimson couturier", "mortal couturier", "starspiral couturier", "shadowsilk couturier"), "weaveshaper"),
]


def infer_class_identifier(e: AuroraElement) -> str:
    """Infer Foundry's system.classIdentifier for an Aurora Archetype."""
    for support in e.supports:
        cid = SUPPORT_TO_CLASS_IDENTIFIER.get((support or "").strip().lower())
        if cid:
            return cid

    # Some elements put the support relationship in a setter-like field or attrs.
    for s in e.setters:
        attrs = s.get("attrs", {}) or {}
        value = str(s.get("value") or s.get("text") or attrs.get("value") or "").strip().lower()
        name = str(attrs.get("name", "")).strip().lower()
        if name in {"class", "parent", "support", "supports", "archetype"}:
            cid = SUPPORT_TO_CLASS_IDENTIFIER.get(value)
            if cid:
                return cid

    upper_id = (e.id or "").upper()
    for hint, cid in ID_HINT_TO_CLASS_IDENTIFIER:
        if hint in upper_id:
            return cid

    path = (e.file or "").replace("_", "-").replace("/", " ").lower()
    for hint, cid in PATH_HINT_TO_CLASS_IDENTIFIER:
        if hint in path:
            return cid

    source_code = (e.source_code or "").upper()
    if source_code in SOURCE_HINT_TO_CLASS_IDENTIFIER:
        return SOURCE_HINT_TO_CLASS_IDENTIFIER[source_code]

    name = (e.name or "").strip().lower()
    for names, cid in NAME_HINT_TO_CLASS_IDENTIFIER:
        if name in names:
            return cid

    return ""


def _grant_rules(e: AuroraElement, grant_type: str) -> list[tuple[int, str]]:
    wanted = grant_type.lower()
    out: list[tuple[int, str]] = []
    for rule in e.rules:
        attrs = rule.get("attrs", {}) or {}
        if (rule.get("tag") or "").lower() != "grant":
            continue
        if (attrs.get("type") or "").lower() != wanted:
            continue
        aurora_id = attrs.get("id", "")
        if not aurora_id or is_asi_feature_id(aurora_id) or is_artillerist_cannon_option_id(aurora_id):
            continue
        out.append((parse_level(attrs.get("level")), aurora_id))
    return out


def _group_item_grants(
    e: AuroraElement,
    grant_type: str,
    uuid_by_aurora_id: dict[str, str],
    child_feature_uuids_by_aurora_id: dict[str, list[str]] | None = None,
) -> tuple[dict[int, list[str]], list[str]]:
    grouped: dict[int, list[str]] = defaultdict(list)
    missing: list[str] = []
    for level, aurora_id in _grant_rules(e, grant_type):
        uuid = uuid_by_aurora_id.get(aurora_id)
        if not uuid:
            missing.append(aurora_id)
            continue
        if uuid not in grouped[level]:
            grouped[level].append(uuid)
        if grant_type.lower() in {"archetype feature", "class feature", "racial trait", "feat"}:
            if is_artillerist_cannon_option_id(aurora_id):
                continue
            for child_uuid in (child_feature_uuids_by_aurora_id or {}).get(aurora_id, []):
                if child_uuid not in grouped[level]:
                    grouped[level].append(child_uuid)
    return dict(grouped), missing


def compile_subclass(
    e: AuroraElement,
    include_source_name: bool = True,
    long_source: bool = False,
    feature_uuid_by_aurora_id: dict[str, str] | None = None,
    spell_uuid_by_aurora_id: dict[str, str] | None = None,
    child_feature_uuids_by_aurora_id: dict[str, list[str]] | None = None,
) -> dict:
    display = e.display_name(include_source_name, long_source=long_source)
    base_name = clean_duplicate_name(e.name)
    class_identifier = infer_class_identifier(e)
    seed = f"subclass:{e.id or e.name}:{e.source_code}"

    item = base_item(display, "subclass", "systems/dnd5e/icons/svg/items/subclass.svg")
    item["system"] = {
        "description": {"value": e.description_html, "chat": ""},
        "source": {"custom": e.source, "book": e.source_code, "page": "", "license": "", "rules": "2014", "revision": 1},
        "identifier": slugify(base_name),
        "classIdentifier": class_identifier,
        "advancement": {},
        "spellcasting": {"progression": "none", "ability": "", "preparation": {"formula": ""}},
    }

    advancements: dict[str, dict] = {}
    missing_features: list[str] = []
    missing_spells: list[str] = []

    if feature_uuid_by_aurora_id is not None:
        grouped, missing_features = _group_item_grants(e, "Archetype Feature", feature_uuid_by_aurora_id, child_feature_uuids_by_aurora_id)
        for level, uuids in sorted(grouped.items()):
            doc = adv.item_grant(seed, uuids, level=level, title="Subclass Features")
            advancements[doc["_id"]] = doc

    if spell_uuid_by_aurora_id is not None:
        grouped, missing_spells = _group_item_grants(e, "Spell", spell_uuid_by_aurora_id)
        for level, uuids in sorted(grouped.items()):
            doc = adv.item_grant(seed, uuids, level=level, title="Subclass Spells")
            # Most subclass spell grants are always prepared; keep the raw grant data in flags for later refinement.
            advancements[doc["_id"]] = doc

    item["system"]["advancement"] = advancements
    item["flags"] = {
        "aurora": {
            "id": e.id,
            "source": e.source,
            "sourceCode": e.source_code,
            "file": e.file,
            "type": e.type,
            "rules": e.rules,
            "setters": e.setters,
            "supports": e.supports,
            "compiler": "subclass-v1.2",
            "inferredClassIdentifier": class_identifier,
            "missingSubclassFeatureGrants": missing_features,
            "missingSubclassSpellGrants": missing_spells,
        }
    }
    return item
